### ISSUE TITLE
笔记名导致同步失效问题，急

### ISSUE THREAD

**Issue by YIRU69** [zhaohongxuan/obsidian-weread-plugin#149]
首先感谢大大的付出，
我今天使用这个插件，导入的本地的epub文件，文件名是：Word Power Made Easy: The Complete Handbook for Building a Superior Vocabulary
然后自己做笔记开始进行同步，却同步不了，我使用的是win11 + 最近的插件和ob
显示的错误是：
```
[weread plugin] sync note book error Word Power Made Easy: The Complete Handbook for Building a Superior Vocabulary Error: File name cannot contain any of the following characters: * " \ / < > : | ?
    at Ne (app.js:1:250336)
    at t.checkPath (app.js:1:1122662)
    at t.<anonymous> (app.js:1:1125323)
    at app.js:1:235836
    at Object.next (app.js:1:235941)
    at app.js:1:234878
    at new Promise (<anonymous>)
    at v (app.js:1:234623)
    at t.createFolder (app.js:1:1125213)
    at y.eval (plugin:obsidian-weread-plugin:2:313479)
```

**Comment by zhaohongxuan** [comment]
文件名中不能包含冒号，去掉冒号或者改成中文冒号

**Comment by YIRU69** [comment]
谢谢，我查到了，是win 系统不能存在这样的字符
