### ISSUE TITLE
【报错】有个别书籍无法创建并同步笔记

### ISSUE THREAD

**Issue by XunLi322** [zhaohongxuan/obsidian-weread-plugin#234]
大概是书籍名字的原因，麻烦大佬看一下，谢谢（鞠躬）。

DevTools failed to load source map: Could not load content for app://obsidian.md/styles.css.map: System error: net::ERR_FILE_NOT_FOUND

Folder 2.📚文献笔记/A001 阅读/Weread/门阀|“中古第一家族”琅琊王氏传承千年的成事智慧（独家首发） not found. Will be created

[weread plugin] sync note book error 门阀|“中古第一家族”琅琊王氏传承千年的成事智慧（独家首发） Error: File name cannot contain any of the following characters: * " \ / < > : | ?
    at jy (app.js:1:696095)
    at t.checkPath (app.js:1:703345)
    at t.<anonymous> (app.js:1:706008)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at t.createFolder (app.js:1:705896)
    at w.eval (plugin:obsidian-weread-plugin:2:365311)
    at Generator.next (<anonymous>)
    at a (plugin:obsidian-weread-plugin:2:355386)

**Comment by zhaohongxuan** [comment]
我这边同步是没有问题的，我看书名里面的引号是中文的，生成的markdown文件也是中文的
<img width="920" alt="image" src="https://github.com/zhaohongxuan/obsidian-weread-plugin/assets/8613196/3a21a4ff-7851-45a5-b5f1-7ac1a0706f84">

**Comment by zhaohongxuan** [comment]
很奇怪，应该是书库里的同一本书吧，怎么你的会有一个“|”呢？

> 我这边应该是因为书籍名称里面有个“|”，所以出错了

**Comment by XunLi322** [comment]
微信读书里面的书名全称就是《门阀|“中古第一家族”琅琊王氏传承千年的成事智慧（独家首发）》，你是不是设置过css之类的啦？无法在obsidian中创建的符号就自动忽略之类的
