### ISSUE TITLE
[BUG]点击登录，可以成功登录，但是同步的时候提示错误Uncaught InvalidStateError

### ISSUE THREAD

**Issue by AlexyYoung** [zhaohongxuan/obsidian-weread-plugin#348]
操作过程如下：
安装好weread插件后，点击登录，扫码，登录成功。
但是插件配置界面没有显示登录成功，还是现实登录2个字，但是弹出的页面显示已经登录成功，如下图：
![image](https://github.com/user-attachments/assets/24823037-ab58-401e-8316-300b629b91c1)

打开控制台提示错误信息如下：
app.js:1 Uncaught InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.<anonymous> (app.js:1:1874830)
    at t.saveFileCache (app.js:1:1892213)
    at t.onCreateOrModify (app.js:1:1891161)
    at t.onCreate (app.js:1:1889544)
    at t.tryTrigger (app.js:1:723006)
    at t.trigger (app.js:1:722939)
    at t.trigger (app.js:1:741044)
    at t.onChange (app.js:1:731108)
    at e.trigger (app.js:1:545565)
    at e.<anonymous> (app.js:1:543637)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at app.js:1:236249
    at new Promise (<anonymous>)
    at g (app.js:1:235994)
    at e.reconcileFileCreation (app.js:1:543114)
    at e.<anonymous> (app.js:1:542755)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)

**Comment by jtsang4** [comment]
我遇到相同问题是因为登录错微信号了，登了一个没有微信读书划线的小号，换成大号以后就好了

**Comment by thinkercjf** [comment]
遇到类似的问题，症状一样，控制台显示的错误有所区别：
同步微信读书笔记异常 Error: get weread note book error after retry
![Screenshot from 2024-12-31 17-55-52](https://github.com/user-attachments/assets/93065634-d1bd-4324-995a-58b68727ef8f)

**Comment by LibraVan** [comment]
之前notion同步出现了类似的问题，是因为微信读书把用户相关cookie的索引和位置改变了，感觉这次是类似，希望大佬有时间修复一下版本。

**Comment by MichaelChou98** [comment]
同样无法正常同步，提示cookie过期![Image](https://github.com/user-attachments/assets/7710387f-6219-4d8c-8d62-753a4579c32f)

**Comment by Ncat-DT** [comment]
> 无法正常同步，提示cookie期间同样![Image](https://github.com/user-attachments/assets/7710387f-6219-4d8c-8d62-753a4579c32f)

请问这个解决了嘛，我这现在也是显示这个问题

**Comment by lonelygo** [comment]
‌‌‌‌‌‌Same issue, awaiting fix.

**Comment by thinkercjf** [comment]
验证成功。感谢！

补充一下，我之前是已经登录了的，在弹出窗口（网页版）里可以看到书架。需要在那里点头像先“退出登录”，然后再在 插件那里点登录才会弹出扫码窗口。

**Comment by mars704** [comment]
> [@AlexyYoung](https://github.com/AlexyYoung) [@thinkercjf](https://github.com/thinkercjf) [@MichaelChou98](https://github.com/MichaelChou98) [@Ncat-DT](https://github.com/Ncat-DT) 做了些尝试，应该是登录的处理有一些“不符合直觉”的地方，不知道是API的限制还是什么原因，但是能解决“登录”后不能同步的问题。具体操作步骤： 1、点“登录”在弹出窗口扫码登录； 2、登录成功后，在弹出窗口，随便找本书“点”一下，弹出窗口会自动消失；这时候插件设置的“登录”位置变成：
> 
> ![Image](https://github.com/user-attachments/assets/7f86d9dd-ae7c-420e-853c-10b44f3e3f0f)
> 
> 这样，就可以正常同步了。
> 
> EOF
> 
> > ‌‌‌‌‌‌Same issue, awaiting fix.

这个办法我这面尝试还是有问题，登录成功也可以看到 Cookie，但是同步的时候好像又自动登出了。

以前通过注销、重新登录的办法还可以解决，最近两天这个办法也没用了。

就报错：[weread plugin] cookie已失效，清理cookie...

**Comment by yunxi177** [comment]
> > [@AlexyYoung](https://github.com/AlexyYoung) [@thinkercjf](https://github.com/thinkercjf) [@MichaelChou98](https://github.com/MichaelChou98) [@Ncat-DT](https://github.com/Ncat-DT) 做了些尝试，应该是登录的处理有一些“不符合直觉”的地方，不知道是API的限制还是什么原因，但是能解决“登录”后不能同步的问题。具体操作步骤： 1、点“登录”在弹出窗口扫码登录； 2、登录成功后，在弹出窗口，随便找本书“点”一下，弹出窗口会自动消失；这时候插件设置的“登录”位置变成：
> > ![Image](https://github.com/user-attachments/assets/7f86d9dd-ae7c-420e-853c-10b44f3e3f0f)
> > 这样，就可以正常同步了。
> > EOF
> > > ‌‌‌‌‌‌Same issue, awaiting fix.
> 
> 这个办法我这面尝试还是有问题，登录成功也可以看到 Cookie，但是同步的时候好像又自动登出了。
> 
> 以前通过注销、重新登录的办法还可以解决，最近两天这个办法也没用了。
> 
> 就报错：[weread plugin] cookie已失效，清理cookie...

遇到了一样的问题
