### ISSUE TITLE
整个删除笔记文件夹之后，重新同步出错

### ISSUE THREAD

**Issue by gongkaizh** [zhaohongxuan/obsidian-weread-plugin#85]
plugin:obsidian-weread-plugin:2 同步微信读书笔记异常 TypeError: Cannot read properties of undefined (reading 'chapters')
    at eval (plugin:obsidian-weread-plugin:2:498323)
    at b.eval (plugin:obsidian-weread-plugin:2:498910)
    at Generator.next (<anonymous>)
    at o (plugin:obsidian-weread-plugin:2:487165)
eval @ plugin:obsidian-weread-plugin:2
a @ plugin:obsidian-weread-plugin:2
plugin:obsidian-weread-plugin:2 get book review error561602 Error: Request failed, status 499
    at new t (app.js:1:1454507)
    at VN (app.js:1:1454662)
    at app.js:1:1455339
    at app.js:1:235078
    at Object.next (app.js:1:235183)
    at s (app.js:1:233922)
eval @ plugin:obsidian-weread-plugin:2
a @ plugin:obsidian-weread-plugin:2

**Comment by gongkaizh** [comment]
第一次试的时候报上面的错，但是第二次试，过了两三分钟，就又开始正常同步了。不知道什么原因。目前正常了

**Comment by zhaohongxuan** [comment]
499是请求没有拿到结果，可能是网络问题。
